# Build stage
FROM golang:1.26-alpine AS builder
ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
# RUN go build -o /app binancee.go
RUN go build -o server ./cmd/server

# Final lightweight stage
FROM alpine:3.21
# COPY --from=builder /app /bin/app
COPY --from=builder /app/server .
COPY --from=builder /app/migrations ./migrations
EXPOSE 8000
CMD ["bin/app"]